In [2]:
import numpy as np
a = np.array(input().split(), dtype=float)
print(a)

[1. 2. 3.]


In [3]:
t = np.array([1, 2, 3])
print(t)
t = np.ones(3)
print(t)
t = np.zeros(3)
print(t)

[1 2 3]
[1. 1. 1.]
[0. 0. 0.]


Вход: в первой строчке шесть чисел координаты точки начала и конца первого вектора x1, y1, z1 и x2, y2, z2, во второй строчке координаты для второго вектора.

Выход: True, если вектора равны, иначе False.

In [5]:
data = input().split(' ')
n = len(data)
d1p1 = np.array(data[:n/2], dtype=int)
d1p2 = np.array(data[n/2:], dtype=int)
d1 = d1p2 - d1p1
data = input().split(' ')
n = len(data)
d2p1 = np.array(data[:n/2], dtype=int)
d2p2 = np.array(data[n/2:], dtype=int)
d2 = d2p2 - d2p1 
np.all(d2==d1)

TypeError: slice indices must be integers or None or have an __index__ method